name: Deploy Testnet (Hardhat)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Pin Hardhat & Toolbox versions
        run: |
          npm pkg set devDependencies.hardhat=2.26.3
          npm pkg set devDependencies["@nomicfoundation/hardhat-toolbox"]=6.1.0
          npm pkg set devDependencies.typescript=5.4.5
          npm pkg set devDependencies.ts-node=10.9.1
          npm pkg set devDependencies["@types/node"]=20.11.30
          npm pkg set dependencies["@openzeppelin/contracts"]=5.0.2

      - name: Install deps
        run: npm i

      - name: Compile
        run: npx hardhat clean && npx hardhat compile

      - name: Deploy to BSC Testnet
        env:
          DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
          RPC_BSC_TESTNET: ${{ vars.RPC_BSC_TESTNET }}
          TREASURY: ${{ vars.TREASURY }}
          GUARDIAN: ${{ vars.GUARDIAN }}
          USDT_ADDRESS_TESTNET: ${{ vars.USDT_ADDRESS_TESTNET }}
          USDT_DECIMALS_TESTNET: ${{ vars.USDT_DECIMALS_TESTNET }}
          PERMIT2: ${{ vars.PERMIT2 }}
        run: npx hardhat run scripts/deploy_testnet.ts --network bscTestnet
