name: Deploy Testnet (Hardhat)

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  # RPC fixed here (secrets में भी रख सकते हैं, पर यह पब्लिक endpoint है)
  RPC_BSC_TESTNET: https://data-seed-prebsc-1-s1.binance.org:8545

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # वही टूलचेिन जो हमारे सफल रन में था
      - name: Pin Hardhat & Toolbox versions
        run: |
          npm pkg set devDependencies.hardhat=2.26.3
          npm pkg set devDependencies["@nomicfoundation/hardhat-toolbox"]=6.1.0
          npm pkg set devDependencies.typescript=5.4.5
          npm pkg set devDependencies.ts-node=10.9.1
          npm pkg set devDependencies["@types/node"]=20.11.30
          npm pkg set dependencies["@openzeppelin/contracts"]=5.0.2

      # CommonJS मोड (पहले भी यहीं से errors solve हुए)
      - name: Force CommonJS (package.json + tsconfig)
        run: |
          node -e "let fs=require('fs');let p=JSON.parse(fs.readFileSync('package.json','utf8'));p.type='commonjs';fs.writeFileSync('package.json',JSON.stringify(p,null,2));"
          sed -i 's/"module": *"NodeNext"/"module": "commonjs"/' tsconfig.json || true
          sed -i 's/"moduleResolution": *"NodeNext"/"moduleResolution": "node"/' tsconfig.json || true

      - run: npm i

      - name: Compile
        run: npx hardhat clean && npx hardhat compile

      - name: Deploy to BSC Testnet
        run: npx hardhat run scripts/deploy_testnet.ts --network bscTestnet
        env:
          DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
          RPC_BSC_TESTNET: ${{ env.RPC_BSC_TESTNET }}
          TREASURY: ${{ vars.TREASURY }}
          GUARDIAN: ${{ vars.GUARDIAN }}
          USDT_ADDRESS_TESTNET: ${{ secrets.USDT_ADDRESS_TESTNET }}
          USDT_DECIMALS_TESTNET: ${{ secrets.USDT_DECIMALS_TESTNET }}
          PERMIT2: ${{ secrets.PERMIT2 }}
