name: Deploy Testnet (Hardhat)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Peer deps की समस्याओं से बचने के लिए versions pin करें (देखें पुराने लॉग्स)
      - name: Pin Hardhat & Toolbox versions
        run: |
          npm pkg set devDependencies.hardhat=2.26.3
          npm pkg set devDependencies["@nomicfoundation/hardhat-toolbox"]=6.1.0
          npm pkg set devDependencies.typescript=5.4.5
          npm pkg set devDependencies.ts-node=10.9.1
          npm pkg set devDependencies["@types/node"]=20.11.30
          npm pkg set dependencies["@openzeppelin/contracts"]=5.0.2

      # Hardhat को CJS मोड में मजबूर करें (ESM/HJH19 errors से बचाव)
      - name: Force CommonJS (package.json + tsconfig)
        run: |
          node -e "let fs=require('fs');let p=JSON.parse(fs.readFileSync('package.json','utf8'));p.type='commonjs';fs.writeFileSync('package.json',JSON.stringify(p,null,2));"
          sed -i 's/"module": *"NodeNext"/"module": "commonjs"/' tsconfig.json || true
          sed -i 's/"moduleResolution": *"NodeNext"/"moduleResolution": "node"/' tsconfig.json || true

      - name: Install deps
        run: npm i

      - name: Compile
        run: npx hardhat clean && npx hardhat compile

      - name: Deploy to BSC Testnet
        env:
          # secrets/vars से पढ़ें; fallback हमेशा single‑quotes में रखें
          DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
          RPC_BSC_TESTNET: ${{ vars.RPC_BSC_TESTNET || 'https://bsc-testnet.drpc.org' }}
          TREASURY: ${{ vars.TREASURY || '0x05A5bc620D55708776c8B52f38A3F5bf0b9DC420' }}
          GUARDIAN: ${{ vars.GUARDIAN || '0xE77F94010Fb3B01431E18015A1c9A56F74e79998' }}
          USDT_ADDRESS_TESTNET: ${{ vars.USDT_ADDRESS_TESTNET || '' }}
          USDT_DECIMALS_TESTNET: ${{ vars.USDT_DECIMALS_TESTNET || '18' }}
          PERMIT2: ${{ vars.PERMIT2 || '0x0000000000000000000000000000000000000000' }}
        run: |
          npx hardhat run scripts/deploy_testnet.ts --network bscTestnet | tee deploy.log

      # deploy.log से addresses निकालकर repo में addresses/testnet.json लिख दें
      - name: Save addresses to addresses/testnet.json
        run: |
          mkdir -p addresses
          node -e "const fs=require('fs');const t=fs.readFileSync('deploy.log','utf8');
          function m(k){const r=new RegExp('^'+k+': (0x[a-fA-F0-9]{40})','m');const x=t.match(r);return x?x[1]:''}
          const out={USDT:m('USDT'),NBL:m('NBL'),REG:m('REG'),TREE:m('TREE'),POOL:m('POOL'),SALE:m('SALE')};
          fs.writeFileSync('addresses/testnet.json', JSON.stringify(out,null,2));"
          cat addresses/testnet.json

      - name: Upload addresses artifact
        uses: actions/upload-artifact@v4
        with:
          name: addresses-testnet
          path: addresses/testnet.json
